---
# Source: gloo-mesh-enterprise/charts/prometheus/templates/server/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: "server"
    app: prometheus
    release: gloo-mesh-enterprise
    chart: prometheus-15.12.2
    heritage: Helm
  name: prometheus-server
  namespace: gloo-mesh
data:
  allow-snippet-annotations: "false"
  alerting_rules.yml: |
    groups:
    - name: GlooPlatformAlerts
      rules:
      - alert: GlooPlatformTranslationLatencyIsHigh
        annotations:
          runbook: https://docs.solo.io/gloo-mesh-enterprise/main/troubleshooting/gloo/
          summary: The translation time has increased above 10 sec. It's currently {{
            $value | humanize }}.
        expr: histogram_quantile(0.99, sum(rate(gloo_mesh_translation_time_sec_bucket[5m]))
          by(le)) > 10
        for: 15m
        labels:
          severity: warning
      - alert: GlooPlatformReconscilerLatencyIsHigh
        annotations:
          runbook: https://docs.solo.io/gloo-mesh-enterprise/main/troubleshooting/gloo/
          summary: The reconciliation time has increased above 80 sec. It's currently
            {{ $value | humanize }}.
        expr: histogram_quantile(0.99, sum(rate(gloo_mesh_reconciler_time_sec_bucket[5m]))
          by(le)) > 80
        for: 15m
        labels:
          severity: warning
      - alert: GlooPlatformAgentsAreDisconnected
        annotations:
          runbook: https://docs.solo.io/gloo-mesh-enterprise/main/troubleshooting/gloo/
          summary: 'The following cluster is disconnected: {{ $labels.cluster }}. Check
            the Gloo Platform Agent pod in the cluster!'
        expr: count by(cluster) (sum by(cluster) (relay_push_clients_warmed == 0)) > 0
        for: 5m
        labels:
          severity: warning
      - alert: GlooPlatformTranslationWarnings
        annotations:
          runbook: https://docs.solo.io/gloo-mesh-enterprise/main/troubleshooting/gloo/
          summary: Gloo Platform has detected {{$value | humanize}} translation warnings
            in the last 5m. Check your {{ $labels.gvk }} resources!
        expr: increase(translation_warning[5m]) > 0
        labels:
          severity: warning
      - alert: GlooPlatformTranslationErrors
        annotations:
          runbook: https://docs.solo.io/gloo-mesh-enterprise/main/troubleshooting/gloo/
          summary: Gloo Platform has detected {{$value | humanize}} translation errors
            in the last 5m. Check your {{ $labels.gvk }} resources!
        expr: increase(translation_error[5m]) > 0
        labels:
          severity: warning
      - alert: GlooPlatformRedisErrors
        annotations:
          runbook: https://docs.solo.io/gloo-mesh-enterprise/main/troubleshooting/gloo/
          summary: Gloo Platform has detected {{$value | humanize}} Redis sync errors
            in the last 5m.
        expr: increase(gloo_mesh_redis_sync_err[5m]) > 0
        labels:
          severity: warning
  alerts: |
    {}
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    - /etc/config/rules
    - /etc/config/alerts
    scrape_configs:
    - job_name: gloo-platform-pods
      kubernetes_sd_configs:
      - namespaces:
          names:
          - gloo-mesh
        role: pod
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: keep
        regex: gloo-mesh-mgmt-server
        source_labels:
        - __meta_kubernetes_pod_label_app
      scrape_interval: 15s
      scrape_timeout: 10s
  recording_rules.yml: |
    {}
  rules: |
    {}
