apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-mgmt
spec:
  destination:
    name: ''
    namespace: gloo-mesh
    server: 'https://kubernetes.default.svc'
  source:
    path: argo/gloo/mgmt-server/template/gloo-mesh-enterprise
    repoURL: 'https://github.com/lamadome/GlooOps.git'
    targetRevision: HEAD
    directory:
      recurse: false
  project: gloo-mesh
  ignoreDifferences:
    - kind: Secret
      name: relay-identity-token-secret
      namespace: gloo-mesh
      jsonPointers:
        - /data/token
    - kind: Secret
      name: relay-root-tls-secret
      namespace: gloo-mesh
      jsonPointers:
        - /data/ca.crt
        - /data/tls.key
    - kind: Secret
      name: relay-server-tls-secret
      namespace: gloo-mesh
      jsonPointers:
        - /data/ca.crt
        - /data/tls.key
        - /data/tls.crt
    - kind: Secret
      name: relay-tls-signing-secret
      namespace: gloo-mesh
      jsonPointers:
        - /data/ca.crt
        - /data/tls.key
        - /data/tls.crt
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
