apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: gloo-mesh
    server: https://kubernetes.default.svc
  project: gloo-mesh
  source:
    path: argo/gloo/mgmt-server/template/prometheus
    repoURL: https://github.com/lamadome/barclays-aws-environment
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
