apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookinfo
  namespace: argocd
spec:
  generators:
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'bookinfo-{{name}}'
    spec:
      project: gloo-mesh
      source:
        repoURL: <repourl>
        targetRevision: HEAD
        path: 'teams/bookinfo/{{name}}'
      destination:
        name: '{{name}}'