apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-cluster2
  namespace: argocd
spec:
  destination:
    name: 'cluster2'
    namespace: gloo-mesh
  source:
    path: ''
    repoURL: 'https://storage.googleapis.com/gloo-mesh-enterprise/gloo-mesh-agent'
    targetRevision: 2.1.2
    chart: gloo-mesh-agent
    helm:
      parameters:
        - name: relay.serverAddress
          value: >-
            localhost:9900
        - name: relay.authority
          value: gloo-mesh-mgmt-server.gloo-mesh
        - name: cluster
          value: cluster2
  project: gloo-mesh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
