apiVersion: v1
kind: Service
metadata:
  labels:
    topology.istio.io/network: cluster2
  name: istio-eastwestgateway
  namespace: istio-gateways
spec:
  selector:
    topology.istio.io/network: cluster2