---
# Source: gloo-mesh-agent/templates/deployment.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo-mesh-agent
  name: gloo-mesh-agent
  namespace: gloo-mesh
---
# Source: gloo-mesh-agent/templates/deployment.yaml
# Service for gloo-mesh-agent

apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo-mesh-agent
  annotations:
    app.kubernetes.io/name: gloo-mesh-agent
  name: gloo-mesh-agent
  namespace: gloo-mesh
spec:
  selector:
    app: gloo-mesh-agent
  type: ClusterIP
  ports:
  - name: http
    port: 9988
  - name: stats
    port: 9091
  - name: grpc
    port: 9977
---
# Source: gloo-mesh-agent/templates/deployment.yaml
---


# Deployment manifest for gloo-mesh-agent

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo-mesh-agent
  annotations:
    app.kubernetes.io/name: gloo-mesh-agent
  name: gloo-mesh-agent
  namespace: gloo-mesh
spec:
  selector:
    matchLabels:
      app: gloo-mesh-agent
  template:
    metadata:
      labels:
        app: gloo-mesh-agent
      annotations:
        app.kubernetes.io/name: gloo-mesh-agent
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: gloo-mesh-agent
      containers:
      - name: gloo-mesh-agent
        image: gcr.io/gloo-mesh/gloo-mesh-agent:2.1.0
        imagePullPolicy: IfNotPresent
        args:
        - run
        - --cluster=cluster2
        - --stats-port=9091
        - --grpc-port=9977
        - --gloo-network-scrape=false
        - --dev-logger=false
        - --relay-address=a83d8bedb78d040c7926349707a67d48-1767189546.eu-west-3.elb.amazonaws.com:9900
        - --relay-authority=gloo-mesh-mgmt-server.gloo-mesh
        - --relay-client-cert-secret-name=relay-client-tls-secret
        - --relay-client-cert-secret-namespace=gloo-mesh
        - --relay-root-cert-secret-name=relay-root-tls-secret
        - --relay-root-cert-secret-namespace=gloo-mesh
        - --relay-identity-token-secret-name=relay-identity-token-secret
        - --relay-identity-token-secret-namespace=gloo-mesh
        - --relay-identity-token-secret-key=token
        - --max-grpc-message-size=4294967295
        - --metrics-buffer-size=50
        - --access-logs-buffer-size=50
        - --relay-insecure=false
        - --verbose=false
        - --leader-election=true
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 10101
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
---
# Source: gloo-mesh-agent/templates/deployment.yaml
# Code generated by skv2. DO NOT EDIT.
