apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gloo-gateways
  namespace: argocd
spec:
  generators:
  - clusters: {}  
  template:
    metadata:
      name: 'istio-lifecycle-{{name}}'
    spec:
      project: gloo-mesh
      source:
        repoURL: <repo-url>
        targetRevision: HEAD
        path: 'teams/platform/istio/{{name}}'
      destination:
        name: '{{name}}'
      automated:
        prune: true
        selfHeal: true