apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-agents
  namespace: argocd
spec:
  destination:
    name: 'mgmt'
    namespace: ''
  source:
    path: gloo/gloo-mesh-agent/files
    repoURL: '<repo-url>'
    targetRevision: HEAD
  project: gloo-mesh
